// src/routes/resume/+page.svelte
<div class="mx-auto w-1/2 gap-1 text-white">
	<h1 class="text-3xl font-medium text-center p-4">Landon Creel | Software Engineer</h1>
	<b>SUMMARY</b>
	<p>An experienced software engineer with a background in API design and development.</p>
	<br />
	<b>EDUCATION</b>
	<br />
	Texas A&M University May 2021 <br />
	B.S. in Computer Science, Minor in Earth Sciences
	<br />
	GPR: 3.686
	<br />
	<br />
	<b>SKILLS</b>
	<br />
	Programming Languages: Java, TypeScript, C/C++, Python, C#, SQL
	<br />
	Other Skills: Spring Boot, Svelte, React, Angular, GraphQL, MongoDB, Docker, Git, Communication
	<br />
	<br />
	<b>EXPERIENCE</b>
	<br />
	<b>Senior Project Professional</b> (October 2025 - Present)
	<br />
	<i>Antea Group</i>
	<br />
	<ul class="list-disc p-4">
		<li>
			Oversaw efforts to modernize document and modernize domain-specific data transformation tools
			utilizing Streamlit UI components
		</li>
		<li>
			Introduced software lifecycle best practices in green team, including test-driven development,
			agile methodology, clean code, and git flow.
		</li>
	</ul>
	<br />
	<b>Software Engineer II</b> (August 2021 - October 2025)
	<br />
	<i>Dell Technologies</i>
	<br />

	<ul class="list-disc p-4">
		<li>
			Worked as part of Agile team to build and maintain scalable API microservices with a total
			weekly volume of 930 million weekly requests using Java, Spring Boot, and Oracle
		</li>
		<li>
			Reduced microservice aggregation response time by a factor of 10 through the creation of a
			GraphQL client application
		</li>
		<li>
			Built and maintained accessible and user-friendly web portals using TypeScript/Angular and
			Java/Spring Boot to facilitate onboarding to RESTful API microservices
		</li>
		<li>
			Reduced major and critical security vulnerabilities from over 50 to 0 overall vulnerabilities
			by completing the upgrade of an Angular 12 application to Angular 15
		</li>
	</ul>
	<b>Java Full-Stack Developer Certification</b> (January 2022 – October 2022)
	<br />
	<i>Simplilearn Industry Bootcamp</i>
	<br />

	<ul class="list-disc p-4">
		<li>
			Participated in 6-month bootcamp of instructor-led courses, guided and solo practice, and
			independent readings to further develop competencies with full-stack development tech
		</li>
		<li>
			React.js, Spring Boot, and MySQL to develop a full-stack e-commerce application as part of a
			solo capstone project
		</li>
	</ul>
	<b>Software Engineering Intern</b> (June 2020 – August 2020)
	<br />
	<i>BP p.l.c</i>
	<br />
	<ul class="list-disc p-4">
		<li>
			Worked in a team of six to develop a full-stack online recruitment platform using Flask,
			MongoDB, and Microsoft Azure for virtualization
		</li>
		<li>
			Wrote Python scripts to parse uploaded resumes, managed Azure virtual machine deployments and
			security, created MongoDB schemas for backend
		</li>
	</ul>
	<b>Computer Science Teaching Assistant</b> (January 2021 - May 2021)
	<br />
	<i>Texas A&M Computer Science Department</i>
	<br />
	<ul class="list-disc p-4">
		<li>Taught C++ in the context of computer systems (memory, synchronization, etc…)</li>
		<li>
			Held office hours to assist students with labs and assignments related to Computer
			Architecture, Computer Systems, and Programming Studio
		</li>
	</ul>
	<b>PROJECTS</b>
	<br />
	<b>ColorClimb Spring 2021</b>
	<br />
	<i>Computer Vision Indoor Climbing Assistant</i>
	<br />
	<ul class="list-disc p-4">
		<li>
			Implemented Python code utilizing OpenCV libraries to identify handhold paths based on color
			to assist colorblind people with path selection in indoor rock climbing
		</li>
		<li>Collaborated with three other developers to develop an iOS app for usage</li>
	</ul>
	<b>TAMU Hack</b> (January 2019)
	<br />
	<i>Facial Recognition Classroom Attendance Solution</i>
	<br />
	<ul class="list-disc p-4">
		<li>Implemented facial recognition using Azure Cognitive Services to identify students</li>
	</ul>
	<b>CodeRed Hackathon</b> (November 2018)
	<br />
	<i>Endless Side-Scrolling Platformer Game</i>
	<br />
	<ul class="list-disc p-4">
		<li>Implemented procedural terrain generation to enable an endless side-scrolling game</li>
		<li>Implemented sprite tiling and created UI themes to create visually appealing graphics</li>
	</ul>
</div>

// src/app/resume/page.tsx
import Layout from "../../components/layout";

export const metadata = {
  title: "Landon Creel | Resume",
};

export default function Resume() {
  return (
    <Layout>
      <b>EDUCATION</b>
      <br />
      Texas A&M University May 2021 <br />
      B.S. in Computer Science, Minor in Earth Sciences
      <br />
      GPR: 3.686
      <br />
      <br />
      <b>SKILLS</b>
      <br />
      Programming Languages: Java, Java/TypeScript, C/C++, Python, C#, SQL
      <br />
      Other Skills: Spring Boot, Angular, GraphQL, React, Git, Communication
      <br />
      <br />
      <b>EXPERIENCE</b>
      <br />
      <b>Software Engineer II</b> (August 2021 - Present)
      <br />
      <i>Dell Technologies</i>
      <br />
      <ul>
        <li>
          Worked as part of Agile team to build and maintain scalable API
          microservices with a total weekly volume of 930 million weekly
          requests using Java, Spring Boot, and Oracle
        </li>
        <li>
          Reduced microservice aggregation response time by a factor of 10
          through the creation of a GraphQL client application
        </li>
        <li>
          Built and maintained accessible and user-friendly web portals using
          TypeScript/Angular and Java/Spring Boot to facilitate onboarding to
          RESTful API microservices
        </li>
        <li>
          Reduced major and critical security vulnerabilities from over 50 to 0
          overall vulnerabilities by completing the upgrade of an Angular 12
          application to Angular 15
        </li>
      </ul>
      <b>Java Full-Stack Developer Certification</b> (January 2022 – October
      2022)
      <br />
      <i>Simplilearn Industry Bootcamp</i>
      <br />
      <ul>
        <li>
          Participated in 6-month bootcamp of instructor-led courses, guided and
          solo practice, and independent readings to further develop
          competencies with full-stack development tech
        </li>
        <li>
          React.js, Spring Boot, and MySQL to develop a full-stack e-commerce
          application as part of a solo capstone project
        </li>
      </ul>
      <b>Software Engineering Intern</b> (June 2020 – August 2020)
      <br />
      <i>BP p.l.c</i>
      <br />
      <ul>
        <li>
          Worked in a team of six to develop a full-stack online recruitment
          platform using Flask, MongoDB, and Microsoft Azure for virtualization
        </li>
        <li>
          Wrote Python scripts to parse uploaded resumes, managed Azure virtual
          machine deployments and security, created MongoDB schemas for backend
        </li>
      </ul>
      <b>Computer Science Teaching Assistant</b> (January 2021 - May 2021)
      <br />
      <i>Texas A&M Computer Science Department</i>
      <br />
      <ul>
        <li>
          Taught C++ in the context of computer systems (memory,
          synchronization, etc…)
        </li>
        <li>
          Held office hours to assist students with labs and assignments related
          to Computer Architecture, Computer Systems, and Programming Studio
        </li>
      </ul>
      <b>PROJECTS</b>
      <br />
      <b>ColorClimb Spring 2021</b>
      <br />
      <i>Computer Vision Indoor Climbing Assistant</i>
      <br />
      <ul>
        <li>
          Implemented Python code utilizing OpenCV libraries to identify
          handhold paths based on color to assist colorblind people with path
          selection in indoor rock climbing
        </li>
        <li>
          Collaborated with three other developers to develop an iOS app for
          usage
        </li>
      </ul>
      <b>TAMU Hack</b> (January 2019)
      <br />
      <i>Facial Recognition Classroom Attendance Solution</i>
      <br />
      <ul>
        <li>
          Implemented facial recognition using Azure Cognitive Services to
          identify students
        </li>
      </ul>
      <b>CodeRed Hackathon</b> (November 2018)
      <br />
      <i>Endless Side-Scrolling Platformer Game</i>
      <br />
      <ul>
        <li>
          Implemented procedural terrain generation to enable an endless
          side-scrolling game
        </li>
        <li>
          Implemented sprite tiling and created UI themes to create visually
          appealing graphics
        </li>
      </ul>
    </Layout>
  );
}
